GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5hbWUiOiJKYWxza2kiLCJlbWFpbCI6ImVtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTY5MTM4MzIyOCwiZXhwIjoxNjkxMzgzMjQzfQ.0pNtXsnpAR5D6z8WKeUczKNPbHZJSPt4q77dgelOVQI
###
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "Jalski",
    "email": "email@gmail.com",
    "password": "100402",
    "confPassword": "100402"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "100402"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout